# Generated by Django 4.0.2 on 2022-02-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0002_salesorder_color_alter_salesorder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
