# Generated by Django 4.0.2 on 2022-02-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0004_remove_salesorder_img_salesorder_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='img_url',
            field=models.CharField(max_length=255),
        ),
    ]
