# Generated by Django 4.0.2 on 2022-02-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0007_salesorder_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballFormOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('img_url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Футбольные формы',
            },
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'verbose_name_plural': 'Бутсы'},
        ),
    ]
