# Generated by Django 4.0.2 on 2022-02-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0008_footballformorder_alter_salesorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
