# Generated by Django 4.0.2 on 2022-02-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0010_alter_salesorder_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
