# Generated by Django 4.0.2 on 2022-02-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0011_alter_salesorder_description_alter_salesorder_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
