# Generated by Django 4.0.2 on 2022-02-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0012_alter_salesorder_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
