# Generated by Django 4.0.2 on 2022-02-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0013_alter_salesorder_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballformorder',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footballformorder',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
