# Generated by Django 4.0.2 on 2022-02-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0014_footballformorder_description_footballformorder_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalKeeperForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(null=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('img_url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Вратарские формы',
            },
        ),
    ]
