# Generated by Django 4.0.2 on 2022-02-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0016_rename_salesorder_product_delete_footballformorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
