# Generated by Django 4.0.2 on 2022-02-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0019_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
