# Generated by Django 4.0.2 on 2022-02-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0020_remove_product_image_product_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='0', upload_to='media/images'),
            preserve_default=False,
        ),
    ]
