# Generated by Django 4.0.2 on 2022-02-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0025_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_url',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
