# Generated by Django 4.0.2 on 2022-02-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0028_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
