# Generated by Django 4.0.2 on 2022-02-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0029_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='0', upload_to='images/'),
            preserve_default=False,
        ),
    ]
