# Generated by Django 4.0.2 on 2022-03-01 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0036_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
